<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ujv6gAbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ujv6gAb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ujv6gAb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'metricsService' => ['privates', 'App\\Service\\MetricsService', 'getMetricsServiceService', true],
        ], [
            'metricsService' => 'App\\Service\\MetricsService',
        ]);
    }
}
