<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SPbkfAMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SPbkfAM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SPbkfAM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lieucampingRepository' => ['privates', 'App\\Repository\\LieucampingRepository', 'getLieucampingRepositoryService', true],
        ], [
            'lieucampingRepository' => 'App\\Repository\\LieucampingRepository',
        ]);
    }
}
