<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OKAda7UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oKAda7U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oKAda7U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'lieucamping' => ['privates', '.errored..service_locator.oKAda7U.App\\Entity\\Lieucamping', NULL, 'Cannot autowire service ".service_locator.oKAda7U": it references class "App\\Entity\\Lieucamping" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'lieucamping' => 'App\\Entity\\Lieucamping',
        ]);
    }
}
