<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClearMetricsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Artprima\PrometheusMetricsBundle\Command\ClearMetricsCommand' shared service.
     *
     * @return \Artprima\PrometheusMetricsBundle\Command\ClearMetricsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/artprima/prometheus-metrics-bundle/Command/ClearMetricsCommand.php';

        $container->privates['Artprima\\PrometheusMetricsBundle\\Command\\ClearMetricsCommand'] = $instance = new \Artprima\PrometheusMetricsBundle\Command\ClearMetricsCommand(($container->privates['prometheus_metrics_bundle.adapter'] ?? $container->getPrometheusMetricsBundle_AdapterService()));

        $instance->setName('artprima:prometheus:metrics:clear');

        return $instance;
    }
}
