<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieucampingTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\LieucampingType' shared autowired service.
     *
     * @return \App\Form\LieucampingType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/LieucampingType.php';

        return $container->privates['App\\Form\\LieucampingType'] = new \App\Form\LieucampingType();
    }
}
