<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricsController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Artprima\PrometheusMetricsBundle\Controller\MetricsController' shared service.
     *
     * @return \Artprima\PrometheusMetricsBundle\Controller\MetricsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/artprima/prometheus-metrics-bundle/Controller/MetricsController.php';
        include_once \dirname(__DIR__, 4).'/vendor/artprima/prometheus-metrics-bundle/Metrics/Renderer.php';

        return $container->services['Artprima\\PrometheusMetricsBundle\\Controller\\MetricsController'] = new \Artprima\PrometheusMetricsBundle\Controller\MetricsController(new \Artprima\PrometheusMetricsBundle\Metrics\Renderer(($container->privates['prometheus_metrics_bundle.collector_registry'] ?? $container->getPrometheusMetricsBundle_CollectorRegistryService())));
    }
}
