<?php

namespace ContainerWdBOCiH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MetricsService' shared autowired service.
     *
     * @return \App\Service\MetricsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/MetricsService.php';

        return $container->privates['App\\Service\\MetricsService'] = new \App\Service\MetricsService();
    }
}
