<?php

namespace Container331LKvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieucampingTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\LieucampingType' shared autowired service.
     *
     * @return \App\Form\LieucampingType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\LieucampingType'] = new \App\Form\LieucampingType();
    }
}
