<?php

namespace Container331LKvw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieucampingRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\LieucampingRepository' shared autowired service.
     *
     * @return \App\Repository\LieucampingRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\LieucampingRepository'] = new \App\Repository\LieucampingRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
