<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container331LKvw\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container331LKvw/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container331LKvw.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container331LKvw\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container331LKvw\App_KernelProdContainer([
    'container.build_hash' => '331LKvw',
    'container.build_id' => '18fb7e9f',
    'container.build_time' => 1736503668,
], __DIR__.\DIRECTORY_SEPARATOR.'Container331LKvw');
