<?php

namespace Container32YJsA0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLieucampingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YgwXu35.App\Entity\Lieucamping' shared service.
     *
     * @return \App\Entity\Lieucamping
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YgwXu35": it references class "App\\Entity\\Lieucamping" but no such service exists.');
    }
}
