controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
camping_centre:
    path: /lieu
    controller: App\Controller\LieuCampingContlollerController::index
