pipeline {
    agent any

    stages {

        stage('Run Conteneurs') {
            steps {
                script {
                    sh 'docker compose up -d'
                }
            }
        }

        stage('Tests') {
            steps {
                script {
                    // On suppose que le service Symfony s'appelle "symfony" dans docker-compose.yml
                    sh 'docker exec symfony php bin/console doctrine:migrations:migrate --no-interaction'
                    sh 'docker exec symfony php bin/phpunit'
                }
            }
        }

        stage('Déploiement') {
            steps {
                script {
                    sh 'docker compose down'
                    sh 'docker compose up -d --build'
                }
            }
        }
    }

    post {
        failure {
            echo "Le déploiement a échoué. Consultez les logs pour plus de détails."
        }
        success {
            echo "Déploiement réussi !"
        }
    }
}
