<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWdBOCiH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWdBOCiH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWdBOCiH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWdBOCiH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWdBOCiH\App_KernelDevDebugContainer([
    'container.build_hash' => 'WdBOCiH',
    'container.build_id' => '886cdec2',
    'container.build_time' => 1745579979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWdBOCiH');
