<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTLL8qaz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTLL8qaz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTLL8qaz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTLL8qaz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTLL8qaz\App_KernelDevDebugContainer([
    'container.build_hash' => 'TLL8qaz',
    'container.build_id' => 'e981309b',
    'container.build_time' => 1735161033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTLL8qaz');
