<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container32YJsA0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container32YJsA0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container32YJsA0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container32YJsA0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container32YJsA0\App_KernelDevDebugContainer([
    'container.build_hash' => '32YJsA0',
    'container.build_id' => '1b06e041',
    'container.build_time' => 1735126160,
], __DIR__.\DIRECTORY_SEPARATOR.'Container32YJsA0');
