<?php

namespace ContainerSBsvjLw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClearMetricsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Artprima\PrometheusMetricsBundle\Command\ClearMetricsCommand' shared service.
     *
     * @return \Artprima\PrometheusMetricsBundle\Command\ClearMetricsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'artprima'.\DIRECTORY_SEPARATOR.'prometheus-metrics-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ClearMetricsCommand.php';

        $container->privates['Artprima\\PrometheusMetricsBundle\\Command\\ClearMetricsCommand'] = $instance = new \Artprima\PrometheusMetricsBundle\Command\ClearMetricsCommand(($container->privates['prometheus_metrics_bundle.adapter'] ?? $container->getPrometheusMetricsBundle_AdapterService()));

        $instance->setName('artprima:prometheus:metrics:clear');

        return $instance;
    }
}
