<?php

namespace ContainerSBsvjLw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMetricsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Artprima\PrometheusMetricsBundle\Controller\MetricsController' shared service.
     *
     * @return \Artprima\PrometheusMetricsBundle\Controller\MetricsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'artprima'.\DIRECTORY_SEPARATOR.'prometheus-metrics-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'MetricsController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'artprima'.\DIRECTORY_SEPARATOR.'prometheus-metrics-bundle'.\DIRECTORY_SEPARATOR.'Metrics'.\DIRECTORY_SEPARATOR.'Renderer.php';

        return $container->services['Artprima\\PrometheusMetricsBundle\\Controller\\MetricsController'] = new \Artprima\PrometheusMetricsBundle\Controller\MetricsController(new \Artprima\PrometheusMetricsBundle\Metrics\Renderer(($container->privates['prometheus_metrics_bundle.collector_registry'] ?? $container->getPrometheusMetricsBundle_CollectorRegistryService())));
    }
}
