<?php

namespace ContainerW4hkl4y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateExpiredReservationsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\UpdateExpiredReservationsCommand' shared autowired service.
     *
     * @return \App\Command\UpdateExpiredReservationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'UpdateExpiredReservationsCommand.php';

        $container->privates['App\\Command\\UpdateExpiredReservationsCommand'] = $instance = new \App\Command\UpdateExpiredReservationsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $instance->setName('app:update-expired-reservations');

        return $instance;
    }
}
