<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Favorit extends \App\Entity\Favorit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'id_user', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'id_lieu', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'date_fav'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'id_user', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'id_lieu', '' . "\0" . 'App\\Entity\\Favorit' . "\0" . 'date_fav'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Favorit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdUser(\App\Entity\User $idUser): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdUser', [$idUser]);

        return parent::addIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdUser(\App\Entity\User $idUser): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdUser', [$idUser]);

        return parent::removeIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLieu(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLieu', []);

        return parent::getIdLieu();
    }

    /**
     * {@inheritDoc}
     */
    public function addIdLieu(\App\Entity\Lieucamping $idLieu): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addIdLieu', [$idLieu]);

        return parent::addIdLieu($idLieu);
    }

    /**
     * {@inheritDoc}
     */
    public function removeIdLieu(\App\Entity\Lieucamping $idLieu): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeIdLieu', [$idLieu]);

        return parent::removeIdLieu($idLieu);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFav(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFav', []);

        return parent::getDateFav();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFav(\DateTimeInterface $date_fav): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFav', [$date_fav]);

        return parent::setDateFav($date_fav);
    }

}
