<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'date_d', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'date_f', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'lieu_camping', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'nombrePersonnes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'date_d', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'date_f', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'lieu_camping', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Reservation' . "\0" . 'nombrePersonnes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reservation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateD(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateD', []);

        return parent::getDateD();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateD(\DateTimeInterface $date_d): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateD', [$date_d]);

        return parent::setDateD($date_d);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateF(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateF', []);

        return parent::getDateF();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateF(\DateTimeInterface $date_f): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateF', [$date_f]);

        return parent::setDateF($date_f);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuCamping(): ?\App\Entity\Lieucamping
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuCamping', []);

        return parent::getLieuCamping();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuCamping(?\App\Entity\Lieucamping $lieu_camping): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuCamping', [$lieu_camping]);

        return parent::setLieuCamping($lieu_camping);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombrePersonnes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombrePersonnes', []);

        return parent::getNombrePersonnes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombrePersonnes(int $nombrePersonnes): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombrePersonnes', [$nombrePersonnes]);

        return parent::setNombrePersonnes($nombrePersonnes);
    }

}
