<?php

namespace ContainerEjMUgmg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YgwXu35Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YgwXu35' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YgwXu35'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lieucamping' => ['privates', '.errored..service_locator.YgwXu35.App\\Entity\\Lieucamping', NULL, 'Cannot autowire service ".service_locator.YgwXu35": it references class "App\\Entity\\Lieucamping" but no such service exists.'],
        ], [
            'lieucamping' => 'App\\Entity\\Lieucamping',
        ]);
    }
}
